config/routes.rb
Rails.application.routes.draw do
root 'sessions#home'
  resources :users

  resources :goals
  patch '/goals/:id/toggle-status' => 'goals#toggle_status', as: 'toggle_goal'

  resources :sessions, only: [:new, :create]

  delete '/logout' => 'sessions#destroy'
end

app/models/advice.rb
class Advice < ActiveRecord::Base
  belongs_to :goal
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user
  has_many :advices

  after_initialize :set_defaults, unless: :persisted?
  # The set_defaults will only work if the object is new

  def set_defaults
    self.completed = false if self.completed.nil?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :goals
  has_secure_password
  attr_reader :password
  validates :name, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
  def authorize
    unless logged_in?
      redirect_to new_session_path
    end
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :authorize, only: [:index, :new, :show, :edit, :destroy]
  def index
    @goals = Goal.all
    # if !logged_in?
      # redirect_to root_path
    # end
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = current_user.goals.new(goal_params)
    if @goal.save
      redirect_to user_path(current_user)
    end
  end
def destroy
  @goal = Goal.find(params[:id])
  @goal.destroy
  redirect_to user_path(current_user)
end

  def toggle_status
    @goal = Goal.find(params[:id])
    @goal.completed = !@goal.completed
    if @goal.save
      redirect_to user_path(current_user)
    end
  end


  def goal_params
      params.require(:goal).permit(:title, :body, :timeframe, :category)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def home
  end

  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:profile, :show, :edit, :destroy]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path
  end
end
  def edit
  end

  def update
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/destroy.html.erb
<h1>Goals#destroy</h1>
<p>Find me in app/views/goals/destroy.html.erb</p>

app/views/goals/index.html.erb
<h1>You've Found A Hidden Cache of Goals!</h1>
<h2> Wow! Look at all this shit! </h2>
<div class="col-md-4" id="text">
<% @goals.each do |g| %>
<br><hr>
<%= g.id%> <%= g.body %> <%= link_to('x',g, method: :delete)%>
<% end%>
</div>

<style>
body {
  background-image: url('<%= asset_path('minimalist.jpg') %>');
}
h1 {
  font-size: 40px;
  color: white;
  text-align: center;
}
h2 {
  font-size: 32px;
  color: #eaeaea;
  text-align:center;
}
#text {
  text-align:center;
  font-size: 18px;
  color: #d3d3d3;
  padding-top: 10px;
}
</style>

app/views/goals/new.html.erb
<h1>Enter a Goal</h1>
<%= form_for @goal do |g| %>
    <hr>

    <div id="text"> Category: </div><%= g.select(:category, options_for_select([['Physical', 'Physical'], ['Mental', 'Mental'], ['Spiritual', 'Spiritual'], ['Career', 'Career']], "in"), {}, {required: 'true', autofocus: 'true', class: 'form-control'})%>
    <br>
    <div id="text">Time Frame: </div><%= g.select(:timeframe, options_for_select([['Long', 'Long'], ['Medium', 'Medium'], ['Short', 'Short']], "in"), {}, {required: 'true', autofocus: 'true', class: 'form-control'})%>
    <br>
    <div id="text">Goal: </div><%= g.text_field :body, {class: 'form-control'}%>
    <br>

    <%= g.submit %>
<% end %>

<style>
body {
  background-image: url('<%= asset_path('minimalist.jpg') %>');
}

h1 {
  font-size: 40px;
  color: white;
  text-align: center;
}
h2{
  font-size: 32px;
  color: #eaeaea;
  text-align:center;
}
#text {
  font-size: 18px;
  color: #d3d3d3;
  padding-top: 10px;
}
</style>

app/views/goals/show.html.erb
<h1>Goals#show</h1>
<p>Find me in app/views/goals/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Hero</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <%if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Navigate <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'My Goals', user_path(current_user) %> </li>
            <li><%= link_to 'Create a Goal', new_goal_path %> </li>
            <li role="separator" class="divider"></li>
            <% if logged_in? %>
              <%= link_to "Logout", logout_path, {method: "DELETE"} %>
            <% end %>
          </ul>
        </li>
        <% else %>
            <li><%= link_to "Login", new_session_path %></li>
        <% end%>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Do</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/navbar"%>
<div class='container'>
<%= yield %>
</div>

</body>
</html>

app/views/users/index.html.erb
<h1>Hall of Heroes</h1>
<% @users.each_slice(3) do |group| %>
<div class='row'>
<% group.each do |q|  %>
<div class='col-md-4' id="text">
<%= q.name %>  <%= link_to 'View',user_path(q)%></div>
<% end %>
</div>
<% end%>

<style>
body {
  background-image: url('<%= asset_path('minimalist.jpg') %>');
}
h1 {
  font-size: 40px;
  color: white;
  text-align: center;
}
#text {
  text-align:center;
  font-size: 18px;
  color: #d3d3d3;
  padding-top: 10px;
}
</style>

app/views/users/new.html.erb
<h1>Goal: Create Account</h1>
<div id="text">
<%= form_for @user do |u| %>
    <hr>
    <div id="text">  User Name: </div><%= u.text_field :name %><br>
      <div id="text">User Email: </div><%= u.text_field :email %> <br>
      <div id="text">User Password: </div><%= u.password_field :password %></div>
    <br>

    <div class="col-md-2 col-md-offset-5"><%= u.submit %></div>
<% end %>



<style>
body {
  background-image: url('<%= asset_path('minimalist.jpg') %>');
}
h1 {
  font-size: 40px;
  color: white;
  text-align: center;
}
#text {
  text-align:center;
  font-size: 18px;
  color: #d3d3d3;
  padding-top: 10px;
}
</style>

app/views/users/show.html.erb
<h1>Hello <%= @user.name %> </h1>
<div id="text">
<% @user.goals.where(completed: false).each do |g| %>
<br><hr>
Category: <%= g.category %> <br>
Time Frame: <%=g.timeframe%><br>
<%= g.body %> <%= link_to('Remove',g, method: :delete)%>
<%= link_to 'Done', toggle_goal_path(g), method: :patch  %>
<% end%>

<hr>

<% @user.goals.where(completed: true).each do |g| %>
<br><hr>
Category: <%= g.category %> <br>
Time Frame: <%=g.timeframe%><br>
<%= g.body %> <%= link_to('Remove',g, method: :delete)%>
<%= link_to 'Mark Incomplete', toggle_goal_path(g), method: :patch  %>
<% end%>

</div>

<style>
body {
  background-image: url('<%= asset_path('minimalist.jpg') %>');
}
h1 {
  font-size: 40px;
  color: white;
  text-align: center;
}
#text {
  font-size: 18px;
  color: #d3d3d3;
  padding-top: 10px;
}
</style>